/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code401challenges;
import java.lang.*;


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }


    public static int[] insertShiftArray(int[] arr, int num) {
        double midPoint = Math.ceil((arr.length / 2));
        if (arr.length % 2 != 0) {
            midPoint += 1;
        }

        // create a new array of size n+1
        int newarr[] = new int[arr.length + 1];

        for (int i = 0; i < arr.length + 1; i++) {
            if (i < midPoint)
                newarr[i] = arr[i];
            else if (i == midPoint)
                newarr[i] = num;
            else
                newarr[i] = arr[i - 1];
        }
        return newarr;
    }
}